ALTER TABLE "product" DROP CONSTRAINT IF EXISTS "product_pkey" CASCADE;
ALTER TABLE "customer" DROP CONSTRAINT IF EXISTS "customer_pkey" CASCADE;
ALTER TABLE "review" DROP CONSTRAINT IF EXISTS "review_pkey" CASCADE;
ALTER TABLE "review" DROP CONSTRAINT IF EXISTS "fkgce54o0p6uugoc2tev4awewly" CASCADE;
ALTER TABLE "review" DROP CONSTRAINT IF EXISTS "fkiyof1sindb9qiqr9o8npj8klt" CASCADE;

